server:
  port: 8081

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  jackson:
    date-format: org.openapitools.RFC3339DateFormat
    serialization:
      write-dates-as-timestamps: false
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest